version: '3'
services:
    alpineapp:
        build:
          dockerfile: Dockerfile
        ports:
            - 8080:80
        # command: "docker-php-ext-install mysqli"
        volumes:
            - ./dist:/var/www/html:z
        links:
            - 'alpinedb'

    alpinedb:
        image: mariadb:10.8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - alpinedb:/var/lib/mysql
            - ./.docker/data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "rootpwd"

volumes:
    alpinedb:
